# Project information
site_name: 'Kotlin AutoMapper'
site_description: 'Boilerplate-free, type-safe object mapping for Kotlin Multiplatform. A KSP annotation processor that automatically generates conversion code for data, enum, and sealed classes'
site_author: 'Alexander Gorodnikov'
site_url: 'https://jacksever.github.io/kotlin-automapper/'
remote_branch: gh-pages

# Repository
repo_name: 'jacksever/kotlin-automapper'
repo_url: 'https://github.com/jacksever/kotlin-automapper'

# Copyright
copyright: 'Copyright &copy; 2026 Alexander Gorodnikov'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/jacksever/kotlin-automapper'

# Navigation
nav:
  - 'Overview': 'index.md'
  - 'Features': 'features.md'
  - 'Setup': 'setup.md'
  - 'How to Use': 'how-to-use.md'
  - 'Advanced Usage':
      - 'Unidirectional Mapping': 'advanced/unidirectional-mapping.md'
      - 'Customizing Mappings': 'advanced/customizing-mappings.md'
      - 'Custom Type Conversion': 'advanced/custom-type-conversion.md'
  - 'Contributing': 'contributing.md'
  - 'Code of Conduct': 'code_of_conduct.md'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Validations
validation:
  links:
    absolute_links: ignore
  nav:
    omitted_files: ignore
