[versions]
# region Kotlin
org-jetbrains-kotlin = "2.3.0"
# endregion

# region Google
com-google-ksp = "2.3.5"
# endregion

# region Code Generation
com-squareup-kotlinpoet = "2.2.0"
# endregion

# region Maven Publishing
com-vanniktech-maven-publish = "0.36.0"
# endregion

[libraries]
com-squareup-kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "com-squareup-kotlinpoet" }
com-squareup-kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "com-squareup-kotlinpoet" }
google-devtools-ksp-processor-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "com-google-ksp" }

# region Gradle plugins
gradlePlugin-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
gradlePlugin-ksp = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "com-google-ksp" }
gradlePlugin-mavenPublish = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "com-vanniktech-maven-publish" }
gradlePlugin-kotlinJvm = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "org-jetbrains-kotlin" }
gradlePlugin-kotlinMultiplatform = { group = "org.jetbrains.kotlin.multiplatform", name = "org.jetbrains.kotlin.multiplatform.gradle.plugin", version.ref = "org-jetbrains-kotlin" }
# endregion
