# This workflow allows for the manual update and deployment of the documentation to GitHub Pages

name: 'Manually Update Docs'

on:
  # Allows this workflow to be triggered manually from the Actions tab
  workflow_dispatch:

permissions:
  pages: write
  contents: read
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Configures the project for deployment to GitHub Pages
      - name: Configure Pages
        uses: actions/configure-pages@v5

      # Checks out the repository code so the workflow can access it
      - name: Checkout Repository
        uses: actions/checkout@v6
      
      # Sets up the specified Python version
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x

      # Installs the project dependencies
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install zensical

      # Builds the static site using Zensical
      - name: Build Documentation
        run: zensical build --clean

      # Uploads the build artifact for GitHub Pages
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: site

      # Deploys the documentation to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
